### ISSUE TITLE
libmysqlclient package problem on Ubuntu 19.10.3 systems

### ISSUE THREAD

**Issue by Falanteris** [chrisandoryan/Nethive-Project#1]
There's a bug during the execution phase where the program would crash due to
_libmysqlclient_20.0_ package not found in the system.

Using _apt install libmysqlclient-dev_  wont solve the issue.

I think it might be because version 19.10.3 doesn't have the same naming conventions with the older package?.
![issue19-10](https://user-images.githubusercontent.com/36617663/73809069-91b74e80-4804-11ea-9c5a-dee171bf1150.png)

**EDIT** : It goes deep apparently. Re-installing _mysql-python_ package through _python(3) -m pip_ doesn't solve the issue due to a missing package called _ConfigParser_. Strangely enough, my OS apparently had the package already for while now.

![issue19-10-2](https://user-images.githubusercontent.com/36617663/73810247-73ebe880-4808-11ea-9d33-4fd41d6d897b.png)

**Comment by chrisandoryan** [comment]
Have you tried re-installing `mysqlclient`?
You can do so by doing `pip3 uninstall mysqlclient` then `pip3 install mysqlclient` (assuming you're using python3 as in the picture)

**Comment by Falanteris** [comment]
Issue solved, thanks a bunch.
